DZ1 HTTP requests in threads
Fakhrudinov/GitBrain_web pull request #1
Opened 2021-06-18 08:33 UTC by Fakhrudinov

2021-06-24 13:35 UTC, vladimir-shmidt reviewed
хорошо
идею уловил
нужно немного улучшить

2021-06-24 13:35 UTC, vladimir-shmidt commented on DZ1_Treads/ApiHttpGets2File/ApiHttpGets2File/Program.cs
> +            ResponceObject result = new ResponceObject();
это объявление лишнее можно указать в месте использования

2021-06-24 13:35 UTC, vladimir-shmidt commented on DZ1_Treads/ApiHttpGets2File/ApiHttpGets2File/Program.cs
> +                foreach (var respObj in tasks)
что будет если в обном из посто будет ошибка например сервер не оттветил или сеть пропала?

2021-06-24 13:35 UTC, vladimir-shmidt commented on DZ1_Treads/ApiHttpGets2File/ApiHttpGets2File/Program.cs
> +                foreach (var respObj in tasks)
стоит проверить свойство Exception или свойство успешности задачи
https://docs.microsoft.com/ru-ru/dotnet/api/system.threading.tasks.task.iscompletedsuccessfully?view=net-5.0

2021-06-24 13:35 UTC, vladimir-shmidt commented on DZ1_Treads/ApiHttpGets2File/ApiHttpGets2File/Program.cs
> +                foreach (var respObj in tasks)
причем Exception нужно проверять в случае не успеха иначе может сложится все приложение

2021-06-26 09:20 UTC, Fakhrudinov commented on DZ1_Treads/ApiHttpGets2File/ApiHttpGets2File/Program.cs
> +                foreach (var respObj in tasks)
поправил в коммите FIX

2021-07-05 14:00 UTC, vladimir-shmidt requested changes

2021-07-05 14:24 UTC, vladimir-shmidt requested changes
задание ок

2021-07-08 06:35 UTC, merged